services:
    pim_icecatdemo.attributetype.vendor:
            class: Pim\Bundle\IcecatDemoBundle\AttributeType\VendorType
            arguments:
                - "vendor"
                - "entity"
                - @oro_flexibleentity.validator.attribute_constraint_guesser
            tags:
                - { name: oro_flexibleentity.attributetype, alias: pim_icecatdemo_vendor }
