datagrid:
    vendor-grid:
        options:
            entityHint: vendor
        source:
            type: pim_orm
            entity: %pim_catalog.entity.vendor.class%
        columns:
            code:
                label: Code
            label:
                label: Label
            responsible:
                label: Responsible
            created:
                label: Created
                frontend_type: datetime
            updated:
                label: Updated
                frontend_type: datetime
        sorters:
            columns:
                code:
                    data_name: o.code
                label:
                    data_name: o.label
                responsible:
                    data_name: o.responsible
                created:
                    data_name: o.created
                updated:
                    data_name: o.updated
            default:
                code: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC
        filters:
            columns:
                code:
                    type:      string
                    label:     Code
                    data_name: o.code
                label:
                    type: string
                    label: Label
                    data_name: o.label
                responsible:
                    type: string
                    label: Responsible
                    data_name: o.responsible
                created:
                    type: datetime
                    label: Created
                    data_name: o.created
                updated:
                    type: datetime
                    label: Updated
                    data_name: o.updated
