parameters:
#    pim_demo.example.class: Pim\Bundle\IcecatDemoBundle\Example

services:
#    pim_demo.example:
#        class: %pim_demo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
